### ISSUE TITLE
[Feature] Container  페이지 

### ISSUE THREAD

**Issue by dkswndus** [FRONTLINE2024/ADizzi-APP#7]
### 배경
-  탭을 이용하여 Room과 Item을 선택할 수 있습니다.
- Room은 +버튼을 누를 시 방 등록, 수정, 삭제가 가능합니다.
- Item은 모든 아이템 사진을 리스트 형식으로 보여줍니다. 
---
###  ✅ TODO

- [ ] 공통 컴포넌트 구현
- [ ] Container 정적 페이지 구현
- [ ] 버튼 클릭 이벤트 구현
- [ ] 방 등록, 수정, 삭제 구현
