### ISSUE TITLE
[Feature]Container 카메라 모듈 페이지

### ISSUE THREAD

**Issue by dkswndus** [FRONTLINE2024/ADizzi-APP#8]
### 배경
- 카메라 모듈 라이브러리를 가져와서 가구를 사진 찍습니다. 
- 수납장 이름을 등록하여 저장합니다. 
---
###  ✅ TODO

- [ ] 공통 컴포넌트 구현
- [ ] Container  카메라 모듈 정적 페이지 구현
- [ ] 카메라 모듈 가져오기
